package task15b

class UncoveredException(val point: Point) : Throwable() {

}
